### ISSUE TITLE
Boucle unification

### ISSUE THREAD

**Issue by clef-men** [Drup/dowsing#10]
L'unification boucle toujours, en particulier sur un « fold » ("('a -> 'b -> 'b) -> 'a list -> 'b -> 'b") mais aussi sur "int list -> 'a -> unit".

**Comment by Drup** [comment]
On the 2nd case .... actually it's not a loop! It just takes forever

On my install, It hits this unification:
- `'A * int list -> unit`
- `anchor * bitmap * bool * bool * color * color * color * color * color * color * color * color * cursor *  int * int * int * int * int * int * int * int * justification * relief * state * string * string * string * string * Textvariable.textVariable * Textvariable.textVariable * (Protocol.tkArgs list -> 'a) * (unit -> unit) * other185491248 * other185491248 -> 'a`

If I remove one of the types of the megatuple, it solves in 2:27 minutes.
